"use strict";

module.exports = {
  ...require("./budget"),
  ...require("./basicCustomerService"),
  ...require("./agentReplyDraft"),
  ...require("./agentRouter"),
  ...require("./bundleMatcher"),
  ...require("./chatTraining"),
  ...require("./conversationLearning"),
  ...require("./designWorkflow"),
  ...require("./designAutoSubmit"),
  ...require("./inboundWorkflow"),
  ...require("./zhenxiCustomerAutomation"),
  ...require("./humanHandoff"),
  ...require("./identityBinding"),
  ...require("./imageSnapshot"),
  ...require("./lowValueAutomation"),
  ...require("./orderDraft"),
  ...require("./orderFollowupMessage"),
  ...require("./selectionMatcher"),
  ...require("./quoteMessage"),
  ...require("./quoteAcceptance"),
  ...require("./quotePaymentProofReview"),
  ...require("./sendGuard"),
  ...require("./skillCompiler"),
  ...require("./skuImport"),
  ...require("./skuCatalogAudit"),
  ...require("./knowledgeImport"),
  ...require("./knowledgeRag"),
  ...require("./xiaoshiCustomerService"),
  ...require("./wechatWindow"),
  ...require("./wechatWindowEvidence"),
};
