"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), "utf8");

test("AI model center uses a Cherry-style provider workspace with guarded credentials", () => {
  const page = read("apps/web/src/features/system/ai-models-page.tsx");
  const manager = read("apps/web/src/features/system/ai-model-provider-manager.tsx");
  const routing = read("apps/web/src/features/system/ai-model-routing-view.tsx");
  const serverView = read("apps/web/src/features/system/ai-model-server-view.tsx");
  const source = [page, manager, routing, serverView].join("\n");
  const api = read("apps/web/src/lib/api.ts");
  const css = read("apps/web/src/features/system/ai-models-page.module.css");
  const controller = read("apps/api/src/ai/ai-provider.controller.ts");
  const service = read("apps/api/src/ai/ai-provider.service.ts");
  const presets = read("apps/api/src/ai/ai-provider-presets.ts");

  assert.match(page, /按 Cherry Studio 的方式集中管理服务商/);
  assert.match(page, /模型服务商/);
  assert.match(page, /路由规则/);
  assert.match(page, /服务器配置/);
  assert.match(manager, /providerSearch/);
  assert.match(manager, /providerFilter/);
  assert.match(manager, /selectedProvider/);
  assert.match(manager, /搜索服务商或模型/);
  assert.match(manager, /启用全部已保存/);
  assert.match(manager, /配置自定义接口/);
  assert.match(manager, /type="password"/);
  assert.match(manager, /autoComplete="off"/);
  assert.match(manager, /API 地址/);
  assert.match(manager, /当前模型/);
  assert.match(manager, /已保存密钥永不回显/);
  assert.match(manager, /获取模型列表/);
  assert.match(manager, /请先保存该服务商的 API Key/);
  assert.match(manager, /手动输入模型 ID/);
  assert.match(manager, /设为当前/);
  assert.match(manager, /syncingProvider/);
  assert.match(page, /syncAiProviderModels/);
  assert.match(source, /真实测速/);
  assert.match(source, /刷新余额 \/ 费用/);
  assert.match(manager, /真实速度与余额/);
  assert.match(manager, /真实响应耗时/);
  assert.match(manager, /实测输出速度/);
  assert.match(manager, /本月实际费用/);
  assert.match(manager, /真实可用余额/);
  assert.match(manager, /测速时间/);
  assert.match(manager, /余额更新时间/);
  assert.match(page, /provider\.latestTest/);
  assert.match(page, /provider\.latestBalance/);
  assert.match(source, /AliyunBSSReadOnlyAccess/);
  assert.match(source, /OpenAI Admin Key/);
  assert.match(source, /服务器密钥文件/);
  assert.match(source, /data-action-id="ai-models-server-env-generate"/);
  assert.match(source, /data-action-id="ai-models-server-env-copy"/);
  assert.match(page, /可能产生费用、配额消耗和外部审计记录/);
  assert.match(page, /探活失败也不会自动重试/);
  assert.match(page, /readState === "ready"/);
  assert.match(page, /manageAccess\.readState === "ready"/);
  assert.match(page, /manageAccess\.allowed/);
  assert.match(routing, /快速 \/ 低成本/);
  assert.match(routing, /复杂 \/ 高质量/);

  assert.match(api, /baseUrl\?: string/);
  assert.match(api, /\/ai\/providers\/\$\{encodeURIComponent\(provider\)\}\/models\/sync/);
  assert.match(api, /AiProviderModelSyncResult/);
  assert.match(api, /\/ai\/providers\/server-env/);
  assert.match(api, /\/ai\/providers\/status\/probe/);
  assert.match(api, /\/ai\/providers\/\$\{encodeURIComponent\(provider\)\}\/test/);
  assert.match(api, /\/ai\/providers\/\$\{encodeURIComponent\(provider\)\}\/balance/);
  assert.match(api, /\/ai\/providers\/\$\{encodeURIComponent\(provider\)\}\/billing-credential/);

  assert.match(css, /\.manager/);
  assert.match(css, /\.providerSidebar/);
  assert.match(css, /\.providerDetail/);
  assert.match(css, /\.modelList/);
  assert.match(css, /overflow:\s*auto/);
  assert.match(css, /@media \(max-width: 720px\)/);

  assert.match(controller, /@Post\(":provider\/models\/sync"\)[\s\S]*@RequireOperatorCapability\("manage_channels"\)/);
  assert.match(controller, /@Post\(":provider\/credential"\)[\s\S]*apiKey\?: string; baseUrl\?: string; model\?: string/);
  assert.match(controller, /saveProviderCredential\(\{ provider, \.\.\.\(payload \|\| \{\}\) \}\)/);
  assert.match(service, /syncProviderModels/);
  assert.match(service, /cleanProviderBaseUrl/);
  assert.match(service, /providerBaseUrlEnv/);
  assert.match(service, /\/models/);
  assert.match(service, /AbortSignal\.timeout/);
  assert.match(service, /server-ai-provider\.env/);
  assert.match(service, /ai-provider-observations\.json/);
  assert.match(service, /persistProviderObservation/);
  assert.doesNotMatch(service, /providers\.push\(\{[\s\S]{0,500}\bapiKey\s*:/);
  assert.match(presets, /name: "custom_api_1"/);
  assert.match(presets, /CUSTOM_API_BASE/);
  assert.match(presets, /name: "geeknow", label: "GeekNow 中转站"/);
  assert.match(presets, /智能客服独立使用的 OpenAI 兼容中转站/);
  assert.doesNotMatch(source, /localStorage|sessionStorage|console\.(?:log|info|debug)/);
});
