"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

function readProjectFile(relativePath) {
  return fs.readFileSync(path.join(__dirname, "..", relativePath), "utf8");
}

test("training sample review center supports selected batch actions", () => {
  const page = readProjectFile("apps/web/src/app/page.tsx");
  const css = readProjectFile("apps/web/src/app/globals.css");
  const api = readProjectFile("apps/web/src/lib/api.ts");
  const stateSection = page.slice(
    page.indexOf("const [trainingSamples"),
    page.indexOf("const [wechatAccounts"),
  );
  const actionSection = page.slice(
    page.indexOf("function toggleTrainingSampleSelection"),
    page.indexOf("function startSampleEdit"),
  );
  const listSection = page.slice(
    page.indexOf("<strong>训练样本复核</strong>"),
    page.indexOf("<div className=\"sample-list\">"),
  );
  const rowSection = page.slice(
    page.indexOf("visibleTrainingSamples.map"),
    page.indexOf("{editingSampleId === sample.id"),
  );

  assert.match(stateSection, /selectedTrainingSampleIds/);
  assert.match(page, /selectedVisibleTrainingSamples/);
  assert.match(page, /const visibleSkuChangeLogs = useMemo\(/);
  assert.match(page, /skuChangeLogs\.filter\(/);
  assert.match(page, /skuChangeImpactMatchesFilter\(log, skuChangeImpactFilter\)/);
  assert.match(page, /skuChangeMatchesSearch\(log, skuChangeSearch\)/);
  assert.match(page, /const skuChangeImpactFilterCounts = useMemo\(\(\) => \{/);
  assert.match(page, /counts\[option\.value\] = skuChangeLogs\.filter\(\(log\) => skuChangeImpactMatchesFilter\(log, option\.value\)\)\.length/);
  assert.match(actionSection, /selectVisibleTrainingSamples/);
  assert.match(actionSection, /selectTrainingSamplesNeedingReview/);
  assert.match(actionSection, /selectSceneUncertainTrainingSamples/);
  assert.match(actionSection, /clearSelectedTrainingSamples/);
  assert.match(page, /let importSummary = ""/);
  assert.match(page, /let importedChatId = ""/);
  assert.match(page, /let importReviewCount = 0/);
  assert.match(page, /let importedChatFilter: TrainingSampleQualityFilter = "all"/);
  assert.match(page, /sceneUncertainCount = \(result\.samples \|\| \[\]\)\.filter\(\(sample\) => isSceneUncertainTrainingSample\(sample\)\)\.length/);
  assert.match(page, /importReviewCount = chatImportReviewCount\(result\)/);
  assert.match(page, /importedChatFilter = chatImportPreferredQualityFilter\(result\)/);
  assert.match(page, /importSummary = chatImportSceneSummary\(result\)/);
  assert.match(page, /const detailText = skillApplyChangeSummary\(result\)/);
  assert.match(page, /async function compileTrainingSkills\(explicitSuggestionKeys\?: string\[\], scopeLabel = "已选"\)/);
  assert.match(page, /const sourceKeys = explicitSuggestionKeys \|\| selectedSkillSuggestionKeys/);
  assert.match(page, /const suggestionKeys = \[\.\.\.new Set\(sourceKeys\.filter\(\(key\) => validKeys\.has\(key\)\)\)\]/);
  assert.match(page, /const suggestionKeySet = new Set\(suggestionKeys\)/);
  assert.match(page, /skillSuggestions\.filter\(\(suggestion\) => suggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)\)/);
  assert.match(page, /const selectedNeedsReviewSkillSuggestions = selectedSuggestions\.filter\(\(suggestion\) => !isSkillSuggestionAutoSelected\(suggestion\)\)/);
  assert.match(page, /const includeNeedsReview = selectedNeedsReviewSkillSuggestions\.length > 0/);
  assert.match(page, /selectedNeedsReviewSkillSuggestions\.length > 0 &&/);
  assert.match(page, /\$\{scopeLabel\}里有 \$\{selectedNeedsReviewSkillSuggestions\.length\} 条需人工判断的 Skill 建议。确认已经看过证据并继续应用吗？/);
  assert.match(page, /`应用\$\{scopeLabel\} Agent Skill`/);
  assert.match(page, /请先勾选要应用的\$\{scopeLabel\} Skill 建议/);
  assert.match(page, /\$\{scopeLabel\} \$\{result\.selected \?\? suggestionKeys\.length\} 条建议/);
  assert.match(page, /function skillApplyChangeSummary\(result: \{ created\?: Array<Record<string, unknown>>; updated\?: Array<Record<string, unknown>>; skipped\?: Array<Record<string, unknown>> \}\)/);
  assert.match(page, /function skillApplyNamesLabel\(label: string, rows: Array<Record<string, unknown>>\)/);
  assert.match(page, /明细：\$\{parts\.join\("；"\)\}/);
  assert.match(page, /const appliedKeySet = new Set\(suggestionKeys\)/);
  assert.match(page, /setSelectedSkillSuggestionKeys\(\(current\) => current\.filter\(\(key\) => !appliedKeySet\.has\(key\)\)\)/);
  assert.match(page, /function confirmNeedsReviewSkillSuggestion\(suggestion: SkillSuggestion\)/);
  assert.match(page, /if \(isSkillSuggestionAutoSelected\(suggestion\)\) return true/);
  assert.match(page, /这条 Skill 建议需要人工判断：\$\{suggestion\.name\}。确认选中后再人工复核吗？/);
  assert.match(page, /function toggleSkillSuggestion\(key: string, checked: boolean, suggestion\?: SkillSuggestion\)/);
  assert.match(page, /if \(checked && suggestion && !confirmNeedsReviewSkillSuggestion\(suggestion\)\) return/);
  assert.match(page, /className="skill-suggestion-review-note"/);
  assert.match(page, /复核原因/);
  assert.match(page, /suggestion\.quality\?\.reason \|\| skillSuggestionSafetyLabel\(suggestion\)/);
  assert.match(page, /建议动作：先核对客户原话、客服回复和适用场景，再决定是否应用。/);
  assert.match(css, /\.skill-suggestion-review-note/);
  assert.match(page, /filteredSafeSkillSuggestionCount = filteredSkillSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.length/);
  assert.doesNotMatch(page, /autoSelectedSkillSuggestionCount = skillSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.length/);
  assert.match(page, /当前筛选 \{filteredSelectedSkillSuggestionCount\} \/ \{filteredSkillSuggestions\.length\} 条已选/);
  assert.match(page, /当前筛选高可信 \{filteredSafeSkillSuggestionCount\} 条/);
  assert.match(page, /skillSuggestionSafetyFilter, setSkillSuggestionSafetyFilter/);
  assert.match(page, /agentFilteredSkillSuggestions =/);
  assert.match(page, /skillSuggestionSafetyFilter === "safe"/);
  assert.match(page, /skillSuggestionSafetyFilter === "review"/);
  assert.match(page, /Skill 建议可信度筛选/);
  assert.match(page, /全部建议（\{agentFilteredSkillSuggestions\.length\}）/);
  assert.match(page, /高可信（\{agentFilteredSafeSkillSuggestionCount\}）/);
  assert.match(page, /需复核（\{agentFilteredNeedsReviewSkillSuggestionCount\}）/);
  assert.match(page, /const skillSuggestionEmptyTitle = agentFilteredSkillSuggestions\.length \? "当前可信度筛选下没有建议" : "还没有 Skill 建议"/);
  assert.match(page, /可以切回“全部建议”，或换一个 Agent 查看其它 Skill 候选。/);
  assert.match(page, /<strong>\{skillSuggestionEmptyTitle\}<\/strong>/);
  assert.match(page, /<span>\{skillSuggestionEmptyMessage\}<\/span>/);
  assert.match(page, /当前筛选需复核 \{filteredNeedsReviewSkillSuggestionCount\} 条/);
  assert.match(page, /filteredUnselectedSafeSkillSuggestionCount = filteredSkillSuggestions\.filter\(/);
  assert.match(page, /filteredUnselectedNeedsReviewSkillSuggestionCount = filteredSkillSuggestions\.filter\(/);
  assert.match(page, /!isSkillSuggestionAutoSelected\(suggestion\) && !selectedSkillSuggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)/);
  assert.match(page, /isSkillSuggestionAutoSelected\(suggestion\) && !selectedSkillSuggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)/);
  assert.match(page, /function selectSafeSkillSuggestions\(\)/);
  assert.match(page, /filteredSkillSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.map\(skillSuggestionKey\)/);
  assert.match(page, /onClick=\{selectSafeSkillSuggestions\}/);
  assert.match(page, /toggleSkillSuggestion\(skillSuggestionKey\(suggestion\), event\.target\.checked, suggestion\)/);
  assert.match(page, /disabled=\{Boolean\(busy\) \|\| !filteredUnselectedSafeSkillSuggestionCount\}/);
  assert.match(page, /只选当前筛选高可信/);
  assert.match(page, /filteredUnselectedSkillSuggestionCount = Math\.max\(0, filteredSkillSuggestions\.length - filteredSelectedSkillSuggestionCount\)/);
  assert.match(page, /filteredUnselectedNeedsReviewSkillSuggestionCount > 0/);
  assert.match(page, /当前筛选有 \$\{filteredUnselectedNeedsReviewSkillSuggestionCount\} 条需人工判断的 Skill 建议，确认一起选中吗？/);
  assert.match(page, /onClick=\{selectAllSkillSuggestions\} disabled=\{Boolean\(busy\) \|\| !filteredUnselectedSkillSuggestionCount\}/);
  assert.match(page, /全选当前筛选/);
  assert.match(page, /清空当前筛选/);
  assert.match(page, /hiddenSelectedSkillSuggestionCount = Math\.max\(0, selectedSkillSuggestionCount - filteredSelectedSkillSuggestionCount\)/);
  assert.match(page, /function clearHiddenSkillSuggestions\(\)/);
  assert.match(page, /setSelectedSkillSuggestionKeys\(\(current\) => current\.filter\(\(key\) => keys\.has\(key\)\)\)/);
  assert.match(page, /function compileFilteredTrainingSkills\(\)/);
  assert.match(page, /\.filter\(\(key\) => selectedSkillSuggestionKeySet\.has\(key\)\)/);
  assert.match(page, /void compileTrainingSkills\(keys, "当前筛选已选"\)/);
  assert.match(page, /onClick=\{clearHiddenSkillSuggestions\}/);
  assert.match(page, /disabled=\{Boolean\(busy\) \|\| !hiddenSelectedSkillSuggestionCount\}/);
  assert.match(page, /hiddenSelectedSkillSuggestionCount && filteredSelectedSkillSuggestionCount/);
  assert.match(page, /onClick=\{compileFilteredTrainingSkills\}/);
  assert.match(page, /只应用当前/);
  assert.match(page, /function compileAllSelectedTrainingSkills\(\)/);
  assert.match(page, /window\.confirm\(`还有 \$\{hiddenSelectedSkillSuggestionCount\} 条其他 Agent 已选建议，确认一起应用到 Skill 吗？`\)/);
  assert.match(page, /void compileTrainingSkills\(\)/);
  assert.match(page, /onClick=\{compileAllSelectedTrainingSkills\}/);
  assert.match(page, /应用全部已选 Skill/);
  assert.match(page, /应用全部已选/);
  assert.match(page, /hiddenSelectedSkillSuggestionCount\} 条其他 Agent 已选/);
  assert.match(page, /点击“应用全部已选”会一起提交/);
  assert.match(page, /className="training-summary skill-suggestion-hint"/);
  assert.match(page, /当前筛选没有已选建议/);
  assert.match(page, /filteredUnselectedSafeSkillSuggestionCount\} 条/);
  assert.match(page, /filteredNeedsReviewSkillSuggestionCount\} 条需人工判断/);
  assert.match(page, /当前筛选还有 \{filteredUnselectedSkillSuggestionCount\} 条未选建议/);
  assert.match(page, /全选当前筛选”会包含这些未展示建议/);
  assert.match(page, /void changeTrainingSampleQualityFilter\(importedChatFilter, importedChatId\)/);
  assert.match(page, /setMessage\(importSummary \|\|/);
  assert.match(page, /trainingSampleImportFilterId/);
  assert.match(page, /setTrainingSampleImportFilterId\(importId\)/);
  assert.match(page, /importId: trainingSampleImportFilterId \|\| undefined/);
  assert.match(page, /function changeTrainingSampleQualityFilterInReviewScope\(filter: TrainingSampleQualityFilter\)/);
  assert.match(page, /changeTrainingSampleQualityFilter\(filter, trainingSampleImportFilterId\)/);
  assert.match(page, /className="training-import-history"/);
  assert.match(page, /chatImports\.slice\(0, 4\)\.map/);
  assert.match(page, /changeTrainingSampleQualityFilter\(chatImportPreferredQualityFilter\(item\), item\.id\)/);
  assert.match(page, /chatImportSceneSummaryLabel\(item\)/);
  assert.match(page, /function chatImportReviewCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportRejectedCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportReadyCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportNeedsReview\(item: ChatImport\)/);
  assert.match(page, /function chatImportReadyForSkill\(item: ChatImport\)/);
  assert.match(page, /function chatImportSkillSuggestionFilter\(item: ChatImport, suggestions: SkillSuggestion\[\]\)/);
  assert.match(page, /function chatImportPreferredQualityFilter\(item: ChatImport\): TrainingSampleQualityFilter/);
  assert.match(page, /if \(chatImportReviewCount\(item\) > 0\) return "review"/);
  assert.match(page, /chatImportReadyForSkill\(activeTrainingImport\)/);
  assert.match(page, /function focusChatImportSkillSuggestions\(item: ChatImport\)/);
  assert.match(page, /const safeKeys = targetSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.map\(skillSuggestionKey\)/);
  assert.match(page, /setSkillSuggestionAgentFilter\(agentFilter\);\s*setSkillSuggestionSafetyFilter\("all"\);/);
  assert.match(page, /setSkillSuggestionAgentFilter\(agentSuggestionKey\);\s*setSkillSuggestionSafetyFilter\("all"\);/);
  assert.match(page, /setSkillSuggestionAgentFilter\(agent\.agentId \|\| agent\.agentKey \|\| "all"\);\s*setSkillSuggestionSafetyFilter\("all"\);/);
  assert.match(page, /setSelectedSkillSuggestionKeys\(\(current\) => \[\.\.\.new Set\(\[\.\.\.current, \.\.\.safeKeys\]\)\]\)/);
  assert.match(page, /onClick=\{\(\) => focusChatImportSkillSuggestions\(activeTrainingImport\)\}/);
  assert.match(page, /setTrainingWorkbenchView\("skills"\)/);
  assert.match(page, /查看 Skill 进化/);
  assert.match(page, /已确认 \$\{readyCount\} 条，可生成 Skill/);
  assert.match(page, /已切到本次导入列表；确认前不会进入训练/);
  assert.match(page, /activeTrainingImport/);
  assert.match(page, /scopedTrainingOverview/);
  assert.match(listSection, /导入批次：\$\{activeTrainingImport\.name\}/);
  assert.match(listSection, /清除批次/);
  assert.match(actionSection, /batchUpdateTrainingSampleStatus\(status: "ready" \| "review" \| "rejected", scope: "selected" \| "visible"\)/);
  assert.match(actionSection, /batchReviewTrainingSamples/);
  assert.match(actionSection, /trainingSampleSceneBatchWarning\(sceneUncertainCount\)/);
  assert.match(actionSection, /trainingSampleBatchReviewNote\(status, scopeLabel, sceneUncertainCount\)/);
  assert.match(page, /function isTrainingSampleNeedingManualReview\(sample: TrainingSample\)/);
  assert.match(page, /\| "needs_attention"/);
  assert.match(page, /changeTrainingSampleQualityFilter\("needs_attention"\)/);
  assert.match(page, /changeTrainingSampleQualityFilter\("scene_uncertain"\)/);
  assert.match(page, /changeTrainingSampleQualityFilter\(attentionReasonQualityFilter\(reason\)\)/);
  assert.match(page, /function attentionReasonQualityFilter\(reason: \{ code\?: string \}\): TrainingSampleQualityFilter/);
  assert.match(page, /filter === "needs_attention"/);
  assert.match(page, /filter === "scene_uncertain"/);
  assert.match(page, /isSceneUncertainTrainingSample\(sample\)/);
  assert.match(page, /function chatImportSceneSummary\(result: ChatImport\)/);
  assert.match(page, /function chatImportSceneUncertainCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportSceneSummaryLabel\(item: ChatImport\)/);
  assert.match(page, /clearSceneCount = samples\.filter\(\(sample\) => sample\.sceneCheck\?\.status === "clear"\)\.length/);
  assert.match(page, /summary\.sceneUncertainSamples \?\? fallbackCount/);
  assert.match(page, /visibleTrainingRecommendations\(trainingOverview\.recommendations\)/);
  assert.doesNotMatch(page, /trainingOverview\.recommendations\.slice\(0, 2\)/);
  assert.match(page, /function trainingRecommendationPriority\(text: string\)/);
  assert.match(page, /聊天导入样本的场景不够确定\|自动分流记忆/);
  assert.match(page, /className="training-summary-action"/);
  assert.match(page, /setTrainingWorkbenchView\("review"\)/);
  assert.match(page, /查看场景待确认/);
  assert.match(page, /选择场景待确认/);
  assert.match(page, /当前显示样本里没有场景待确认的导入样本/);
  assert.match(page, /请逐条核对 Agent 和场景后再确认训练/);
  assert.match(page, /避免把 A 客户场景训练给 B 智能体/);
  assert.match(page, /已按当前 Agent 和场景人工确认/);
  assert.match(page, /场景待确认/);
  assert.match(page, /isAntiWrongReplyTrainingSample\(sample\) && sample\.status !== "review"/);
  assert.match(page, /className="training-attention-reasons"/);
  assert.match(page, /sampleAttentionReasons\(sample\)/);
  assert.match(page, /sampleSceneEvidence\(sample\)/);
  assert.match(page, /className="sample-scene-check"/);
  assert.match(page, /sampleSceneRouteMemoryBadge\(sample\)/);
  assert.match(page, /人工已确认/);
  assert.match(page, /确认后才分流/);
  assert.match(page, /可训练分流/);
  assert.match(page, /className="sample-attention-reasons"/);
  assert.match(page, /attentionReasonLabel\(reason\)/);
  assert.match(page, /title=\{attentionReasonTitle\(reason\)\}/);
  assert.match(rowSection, /<button\s+type="button"\s+key=\{reason\.code\}/);
  assert.match(rowSection, /onClick=\{\(\) => changeTrainingSampleQualityFilterInReviewScope\(attentionReasonQualityFilter\(reason\)\)\}/);
  assert.match(page, /sceneReasonCodes\.has\(reason\.code \|\| ""\)\) return "scene_uncertain"/);
  assert.match(listSection, /已选 \{selectedVisibleTrainingSamples\.length\} 条/);
  assert.match(listSection, /已选确认/);
  assert.match(listSection, /已选退回复核/);
  assert.match(listSection, /已选禁用/);
  assert.match(listSection, /changeTrainingSampleQualityFilterInReviewScope\(option\.key\)/);
  assert.match(rowSection, /className="sample-check"/);
  assert.match(rowSection, /toggleTrainingSampleSelection\(sample\.id, event\.target\.checked\)/);
  assert.match(css, /\.sample-selection-summary/);
  assert.match(css, /\.sample-check input/);
  assert.match(css, /\.training-attention-reasons/);
  assert.match(css, /\.training-summary-action/);
  assert.match(css, /\.training-summary-action:disabled/);
  assert.match(css, /\.training-import-history/);
  assert.match(css, /\.training-import-row\.needs-review/);
  assert.match(css, /\.training-import-row\.clear/);
  assert.match(css, /\.sample-scene-check/);
  assert.match(css, /\.sample-scene-check span\.route-memory-ok/);
  assert.match(css, /\.sample-scene-check span\.route-memory-blocked/);
  assert.match(css, /\.sample-attention-reasons/);
  assert.match(css, /\.sample-attention-reasons button/);
  assert.match(css, /\.sample-attention-reasons button:disabled/);
  assert.match(api, /sceneUncertainSamples\?: number/);
  assert.match(api, /\| "scene_uncertain"/);
  assert.match(api, /importId\?: string/);
  assert.match(api, /params\.set\("importId", filters\.importId\)/);
  assert.match(api, /sceneSummary\?: \{/);
  assert.match(api, /sceneUncertainCount: number/);
  assert.match(api, /readyCount\?: number/);
  assert.match(api, /reviewCount\?: number/);
  assert.match(api, /rejectedCount\?: number/);
});
