"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

function readProjectFile(relativePath) {
  return fs.readFileSync(path.join(__dirname, "..", relativePath), "utf8");
}

test("training sample review center supports selected batch actions", () => {
  const page = readProjectFile("apps/web/src/app/page.tsx");
  const css = readProjectFile("apps/web/src/app/globals.css");
  const api = readProjectFile("apps/web/src/lib/api.ts");
  const stateSection = page.slice(
    page.indexOf("const [trainingSamples"),
    page.indexOf("const [wechatAccounts"),
  );
  const actionSection = page.slice(
    page.indexOf("function toggleTrainingSampleSelection"),
    page.indexOf("function startSampleEdit"),
  );
  const listSection = page.slice(
    page.indexOf("<strong>训练样本复核</strong>"),
    page.indexOf("<div className=\"sample-list\">"),
  );
  const rowSection = page.slice(
    page.indexOf("visibleTrainingSamples.map"),
    page.indexOf("{editingSampleId === sample.id"),
  );
  const saveEditSection = page.slice(
    page.indexOf("function editedTrainingSampleForConfirm"),
    page.indexOf("async function createSendTask"),
  );

  assert.match(stateSection, /selectedTrainingSampleIds/);
  assert.match(page, /selectedVisibleTrainingSamples/);
  assert.match(page, /const visibleSkuChangeLogs = useMemo\(/);
  assert.match(page, /skuChangeLogs\.filter\(/);
  assert.match(page, /skuChangeImpactMatchesFilter\(log, skuChangeImpactFilter\)/);
  assert.match(page, /skuChangeMatchesSearch\(log, skuChangeSearch\)/);
  assert.match(page, /const skuChangeImpactFilterCounts = useMemo\(\(\) => \{/);
  assert.match(page, /counts\[option\.value\] = skuChangeLogs\.filter\(\(log\) => skuChangeImpactMatchesFilter\(log, option\.value\)\)\.length/);
  assert.match(actionSection, /function trainingSampleSelectionRiskSummary\(samples: TrainingSample\[\], options: \{ includeNeedsAttention\?: boolean \} = \{\}\)/);
  assert.match(actionSection, /samples\.filter\(isTrainingSampleNeedingManualReview\)\.length/);
  assert.match(actionSection, /samples\.filter\(isSceneUncertainTrainingSample\)\.length/);
  assert.match(actionSection, /parts\.push\(`\$\{needsAttentionCount\} 条需处理`\)/);
  assert.match(actionSection, /parts\.push\(`\$\{sceneUncertainCount\} 条场景待确认`\)/);
  assert.match(actionSection, /function selectVisibleTrainingSamples\(\)/);
  assert.match(actionSection, /const riskText = trainingSampleSelectionRiskSummary\(samples, \{ includeNeedsAttention: true \}\)/);
  assert.match(actionSection, /已选择 \$\{samples\.length\} 条当前显示样本\$\{riskText\}\$\{overflowText\}/);
  assert.match(actionSection, /function selectTrainingSamplesNeedingReview\(\)/);
  assert.match(actionSection, /const sceneRiskText = trainingSampleSelectionRiskSummary\(samples, \{ includeNeedsAttention: false \}\)/);
  assert.match(actionSection, /已智能选择 \$\{samples\.length\} 条需处理训练样本\$\{sceneRiskText\}\$\{overflowText\}/);
  assert.match(actionSection, /selectSceneUncertainTrainingSamples/);
  assert.match(actionSection, /clearSelectedTrainingSamples/);
  assert.match(page, /let importSummary = ""/);
  assert.match(page, /let importedChatId = ""/);
  assert.match(page, /let importReviewCount = 0/);
  assert.match(page, /let importedChatFilter: TrainingSampleQualityFilter = "all"/);
  assert.match(page, /sceneUncertainCount = \(result\.samples \|\| \[\]\)\.filter\(\(sample\) => isSceneUncertainTrainingSample\(sample\)\)\.length/);
  assert.match(page, /importReviewCount = chatImportReviewCount\(result\)/);
  assert.match(page, /importedChatFilter = chatImportPreferredQualityFilter\(result\)/);
  assert.match(page, /importSummary = chatImportSceneSummary\(result\)/);
  assert.match(page, /const blockedKeys = new Set\(typedSuggestionRows\.filter\(isSkillSuggestionBlocked\)\.map\(skillSuggestionKey\)\)/);
  assert.match(page, /const kept = current\.filter\(\(key\) => validKeys\.has\(key\) && !blockedKeys\.has\(key\)\)/);
  assert.match(page, /const detailText = skillApplyChangeSummary\(result\)/);
  assert.match(page, /async function compileTrainingSkills\(explicitSuggestionKeys\?: string\[\], scopeLabel = "已选"\)/);
  assert.match(page, /const sourceKeys = explicitSuggestionKeys \|\| selectedSkillSuggestionKeys/);
  assert.match(page, /const suggestionKeys = \[\.\.\.new Set\(sourceKeys\.filter\(\(key\) => validKeys\.has\(key\)\)\)\]/);
  assert.match(page, /const suggestionKeySet = new Set\(suggestionKeys\)/);
  assert.match(page, /skillSuggestions\.filter\(\(suggestion\) => suggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)\)/);
  assert.match(page, /function isSkillSuggestionBlocked\(suggestion: SkillSuggestion\)/);
  assert.match(page, /suggestion\.quality\?\.blocked/);
  assert.match(page, /suggestion\.quality\?\.level === "blocked"/);
  assert.match(page, /suggestion\.scope\?\.level === "mixed"/);
  assert.match(page, /const selectedBlockedSkillSuggestions = selectedSuggestions\.filter\(isSkillSuggestionBlocked\)/);
  assert.match(page, /身份冲突\/混合来源 Skill 建议，不能应用/);
  assert.match(page, /const selectedNeedsReviewSkillSuggestions = selectedSuggestions\.filter\(\(suggestion\) => !isSkillSuggestionAutoSelected\(suggestion\)\)/);
  assert.match(page, /const includeNeedsReview = selectedNeedsReviewSkillSuggestions\.length > 0/);
  assert.match(page, /const selectedSkillSuggestions = skillSuggestions\.filter\(\(suggestion\) => selectedSkillSuggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)\)/);
  assert.match(page, /const selectedSafeSkillSuggestionCount = selectedSkillSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.length/);
  assert.match(page, /const selectedBlockedSkillSuggestionCount = selectedSkillSuggestions\.filter\(isSkillSuggestionBlocked\)\.length/);
  assert.match(page, /const selectedNeedsReviewSkillSuggestionCount = selectedSkillSuggestions\.filter\(/);
  assert.match(page, /!isSkillSuggestionAutoSelected\(suggestion\) && !isSkillSuggestionBlocked\(suggestion\)/);
  assert.match(page, /const reviewPreview = selectedNeedsReviewSkillSuggestions\.slice\(0, 3\)\.map\(skillSuggestionReviewSummary\)\.join\("\\n"\)/);
  assert.match(page, /const moreText = selectedNeedsReviewSkillSuggestions\.length > 3/);
  assert.match(page, /\$\{scopeLabel\}里有 \$\{selectedNeedsReviewSkillSuggestions\.length\} 条需人工判断的 Skill 建议：\\n\$\{reviewPreview\}/);
  assert.match(page, /确认已经看过证据并继续应用吗？/);
  assert.match(page, /`应用\$\{scopeLabel\} Agent Skill`/);
  assert.match(page, /请先勾选要应用的\$\{scopeLabel\} Skill 建议/);
  assert.match(page, /\$\{scopeLabel\} \$\{result\.selected \?\? suggestionKeys\.length\} 条建议/);
  assert.match(page, /const blockedText = skillApplyBlockedSummary\(result\)/);
  assert.match(page, /SkillSuggestionApplyBlocked/);
  assert.match(page, /function skillApplyBlockedSummary\(result: \{ requiresReview\?: number; blocked\?: SkillSuggestionApplyBlocked\[\] \}\)/);
  assert.match(page, /identityBlockedCount \? `身份冲突禁止 \$\{identityBlockedCount\} 条`/);
  assert.match(page, /reviewBlockedCount \? `需复核未应用 \$\{reviewBlockedCount\} 条`/);
  assert.match(page, /function skillApplyBlockedByIdentity\(row: SkillSuggestionApplyBlocked\)/);
  assert.match(page, /row\.reason === "identity_scope_blocked"/);
  assert.match(page, /quality\?\.blocked === true \|\| quality\?\.level === "blocked"/);
  assert.match(page, /function skillApplyChangeSummary\(result: \{ created\?: Array<Record<string, unknown>>; updated\?: Array<Record<string, unknown>>; skipped\?: Array<Record<string, unknown>> \}\)/);
  assert.match(page, /function skillApplyNamesLabel\(label: string, rows: Array<Record<string, unknown>>\)/);
  assert.match(page, /明细：\$\{parts\.join\("；"\)\}/);
  assert.match(api, /skills: Array<\{/);
  assert.match(api, /scope\?: \{[\s\S]*label\?: string;[\s\S]*conversationId\?: string \| null;/);
  assert.match(api, /level: "safe" \| "review" \| "risk" \| "blocked"/);
  assert.match(api, /blocked\?: boolean/);
  assert.match(api, /export type SkillSuggestionApplyBlocked = SkillSuggestion & \{/);
  assert.match(api, /reason: "identity_scope_blocked" \| "needs_review" \| string/);
  assert.match(api, /blocked\?: SkillSuggestionApplyBlocked\[\]/);
  assert.match(page, /function agentSkillScopeTone\(level\?: string\)/);
  assert.match(page, /className=\{`agent-skill-pill \$\{agentSkillScopeTone\(skill\.scope\?\.level\)\}`\}/);
  assert.match(page, /\{skill\.scope\?\.label \? <small>\{skill\.scope\.label\}<\/small> : null\}/);
  assert.match(page, /const appliedKeySet = new Set\(suggestionKeys\)/);
  assert.match(page, /setSelectedSkillSuggestionKeys\(\(current\) => current\.filter\(\(key\) => !appliedKeySet\.has\(key\)\)\)/);
  assert.match(page, /function confirmNeedsReviewSkillSuggestion\(suggestion: SkillSuggestion\)/);
  assert.match(page, /if \(isSkillSuggestionBlocked\(suggestion\)\) \{/);
  assert.match(page, /不能选中应用/);
  assert.match(page, /if \(isSkillSuggestionAutoSelected\(suggestion\)\) return true/);
  assert.match(page, /这条 Skill 建议需要人工判断：\\n\$\{skillSuggestionReviewSummary\(suggestion\)\}\\n确认选中后再人工复核吗？/);
  assert.match(page, /function skillSuggestionReviewSummary\(suggestion: SkillSuggestion\)/);
  assert.match(page, /const reason = suggestion\.quality\?\.reason \|\| skillSuggestionSafetyLabel\(suggestion\)/);
  assert.match(page, /function skillSuggestionEvidencePreview\(value\?: string\)/);
  assert.match(page, /replace\(\/\\s\+\/g, " "\)\.trim\(\)/);
  assert.match(page, /text\.length > 36 \? `\$\{text\.slice\(0, 36\)\}\.\.\.` : text/);
  assert.match(page, /const question = skillSuggestionEvidencePreview\(suggestion\.evidence\?\.question\)/);
  assert.match(page, /const answer = skillSuggestionEvidencePreview\(suggestion\.evidence\?\.answer\)/);
  assert.match(page, /const evidence = question \? `｜客户 \$\{question\}` : answer \? `｜客服 \$\{answer\}` : ""/);
  assert.match(page, /\$\{suggestion\.name\}｜\$\{skillSuggestionScopeLabel\(suggestion\)\}｜\$\{reason\}｜样本 \$\{suggestion\.sampleCount\} 条｜置信度 \$\{suggestion\.confidence\}\$\{evidence\}/);
  assert.match(page, /function toggleSkillSuggestion\(key: string, checked: boolean, suggestion\?: SkillSuggestion\)/);
  assert.match(page, /if \(checked && suggestion && !confirmNeedsReviewSkillSuggestion\(suggestion\)\) return/);
  assert.match(page, /className="skill-suggestion-review-note"/);
  assert.match(page, /复核原因/);
  assert.match(page, /suggestion\.quality\?\.reason \|\| skillSuggestionSafetyLabel\(suggestion\)/);
  assert.match(page, /建议动作：先核对客户原话、客服回复和适用场景，再决定是否应用。/);
  assert.match(css, /\.skill-suggestion-review-note/);
  assert.match(css, /\.skill-row \.agent-skill-pill/);
  assert.match(css, /\.skill-row \.agent-skill-pill small/);
  assert.match(css, /\.skill-row \.agent-skill-pill\.global/);
  assert.match(css, /\.skill-row \.agent-skill-pill\.private/);
  assert.match(css, /\.skill-row \.agent-skill-pill\.risk/);
  assert.match(css, /\.skill-suggestion-row\.blocked/);
  assert.match(css, /\.skill-suggestion-safety\.blocked/);
  assert.match(css, /\.skill-suggestion-review-note\.blocked/);
  assert.match(page, /filteredSafeSkillSuggestionCount = filteredSkillSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.length/);
  assert.match(page, /agentFilteredBlockedSkillSuggestionCount = agentFilteredSkillSuggestions\.filter\(isSkillSuggestionBlocked\)\.length/);
  assert.match(page, /filteredBlockedSkillSuggestionCount = filteredSkillSuggestions\.filter\(isSkillSuggestionBlocked\)\.length/);
  assert.doesNotMatch(page, /autoSelectedSkillSuggestionCount = skillSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.length/);
  assert.match(page, /当前筛选 \{filteredSelectedSkillSuggestionCount\} \/ \{filteredSkillSuggestions\.length\} 条已选/);
  assert.match(page, /已选高可信 \{selectedSafeSkillSuggestionCount\} 条，已选需复核 \{selectedNeedsReviewSkillSuggestionCount\} 条，已选禁止 \{selectedBlockedSkillSuggestionCount\} 条/);
  assert.match(page, /当前筛选高可信 \{filteredSafeSkillSuggestionCount\} 条/);
  assert.match(page, /skillSuggestionSafetyFilter, setSkillSuggestionSafetyFilter/);
  assert.match(page, /agentFilteredSkillSuggestions =/);
  assert.match(page, /skillSuggestionSafetyFilter === "safe"/);
  assert.match(page, /skillSuggestionSafetyFilter === "review"/);
  assert.match(page, /skillSuggestionSafetyFilter === "blocked"/);
  assert.match(page, /Skill 建议可信度筛选/);
  assert.match(page, /全部建议（\{agentFilteredSkillSuggestions\.length\}）/);
  assert.match(page, /高可信（\{agentFilteredSafeSkillSuggestionCount\}）/);
  assert.match(page, /需复核（\{agentFilteredNeedsReviewSkillSuggestionCount\}）/);
  assert.match(page, /身份冲突（\{agentFilteredBlockedSkillSuggestionCount\}）/);
  assert.match(page, /const skillSuggestionEmptyTitle = agentFilteredSkillSuggestions\.length \? "当前可信度筛选下没有建议" : "还没有 Skill 建议"/);
  assert.match(page, /可以切回“全部建议”，或换一个 Agent 查看其它 Skill 候选。/);
  assert.match(page, /<strong>\{skillSuggestionEmptyTitle\}<\/strong>/);
  assert.match(page, /<span>\{skillSuggestionEmptyMessage\}<\/span>/);
  assert.match(page, /当前筛选需复核 \{filteredNeedsReviewSkillSuggestionCount\} 条，当前筛选身份冲突 \{filteredBlockedSkillSuggestionCount\} 条/);
  assert.match(page, /filteredUnselectedSafeSkillSuggestionCount = filteredSkillSuggestions\.filter\(/);
  assert.match(page, /filteredUnselectedNeedsReviewSkillSuggestionCount = filteredSkillSuggestions\.filter\(/);
  assert.match(page, /!isSkillSuggestionAutoSelected\(suggestion\) &&\s*!isSkillSuggestionBlocked\(suggestion\) &&\s*!selectedSkillSuggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)/);
  assert.match(page, /isSkillSuggestionAutoSelected\(suggestion\) && !selectedSkillSuggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)/);
  assert.match(page, /function selectSafeSkillSuggestions\(\)/);
  assert.match(page, /filteredSkillSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.map\(skillSuggestionKey\)/);
  assert.match(page, /onClick=\{selectSafeSkillSuggestions\}/);
  assert.match(page, /toggleSkillSuggestion\(skillSuggestionKey\(suggestion\), event\.target\.checked, suggestion\)/);
  assert.match(page, /disabled=\{Boolean\(busy\) \|\| !filteredUnselectedSafeSkillSuggestionCount\}/);
  assert.match(page, /只选当前筛选高可信/);
  assert.match(page, /filteredSelectableSkillSuggestionCount = filteredSkillSuggestions\.filter\(\(suggestion\) => !isSkillSuggestionBlocked\(suggestion\)\)\.length/);
  assert.match(page, /filteredSelectedBlockedSkillSuggestionCount = filteredSkillSuggestions\.filter\(/);
  assert.match(page, /filteredUnselectedSkillSuggestionCount = Math\.max\(/);
  assert.match(page, /filteredUnselectedNeedsReviewSkillSuggestionCount > 0/);
  assert.match(page, /const selectableSuggestions = filteredSkillSuggestions\.filter\(\(suggestion\) => !isSkillSuggestionBlocked\(suggestion\)\)/);
  assert.match(page, /const reviewSuggestions = selectableSuggestions\.filter\(/);
  assert.match(page, /!isSkillSuggestionAutoSelected\(suggestion\) && !selectedSkillSuggestionKeySet\.has\(skillSuggestionKey\(suggestion\)\)/);
  assert.match(page, /const reviewPreview = reviewSuggestions\.slice\(0, 3\)\.map\(skillSuggestionReviewSummary\)\.join\("\\n"\)/);
  assert.match(page, /const moreText = reviewSuggestions\.length > 3/);
  assert.match(page, /当前筛选有 \$\{filteredUnselectedNeedsReviewSkillSuggestionCount\} 条需人工判断的 Skill 建议：\\n\$\{reviewPreview\}/);
  assert.match(page, /确认一起选中吗？/);
  assert.match(page, /onClick=\{selectAllSkillSuggestions\} disabled=\{Boolean\(busy\) \|\| !filteredUnselectedSkillSuggestionCount\}/);
  assert.match(page, /全选当前筛选/);
  assert.match(page, /清空当前筛选/);
  assert.match(page, /filteredSkillSuggestionKeySet = new Set\(filteredSkillSuggestions\.map\(skillSuggestionKey\)\)/);
  assert.match(page, /hiddenSelectedSkillSuggestions = selectedSkillSuggestions\.filter\(/);
  assert.match(page, /hiddenSelectedSkillSuggestionCount = hiddenSelectedSkillSuggestions\.length/);
  assert.match(page, /hiddenBlockedSkillSuggestions = hiddenSelectedSkillSuggestions\.filter\(isSkillSuggestionBlocked\)/);
  assert.match(page, /hiddenBlockedSkillSuggestionCount = hiddenBlockedSkillSuggestions\.length/);
  assert.match(page, /hiddenNeedsReviewSkillSuggestions = hiddenSelectedSkillSuggestions\.filter/);
  assert.match(page, /hiddenNeedsReviewSkillSuggestionCount = hiddenNeedsReviewSkillSuggestions\.length/);
  assert.match(page, /function clearHiddenSkillSuggestions\(\)/);
  assert.match(page, /setSelectedSkillSuggestionKeys\(\(current\) => current\.filter\(\(key\) => keys\.has\(key\)\)\)/);
  assert.match(page, /function compileFilteredTrainingSkills\(\)/);
  assert.match(page, /\.filter\(\(key\) => selectedSkillSuggestionKeySet\.has\(key\)\)/);
  assert.match(page, /void compileTrainingSkills\(keys, "当前筛选已选"\)/);
  assert.match(page, /onClick=\{clearHiddenSkillSuggestions\}/);
  assert.match(page, /disabled=\{Boolean\(busy\) \|\| !hiddenSelectedSkillSuggestionCount\}/);
  assert.match(page, /hiddenSelectedSkillSuggestionCount && filteredSelectedSkillSuggestionCount/);
  assert.match(page, /onClick=\{compileFilteredTrainingSkills\}/);
  assert.match(page, /只应用当前/);
  assert.match(page, /function compileAllSelectedTrainingSkills\(\)/);
  assert.match(page, /if \(hiddenBlockedSkillSuggestionCount > 0\) \{/);
  assert.match(page, /hiddenBlockedPreview = hiddenBlockedSkillSuggestions\.slice\(0, 3\)\.map\(skillSuggestionReviewSummary\)\.join\("\\n"\)/);
  assert.match(page, /其他 Agent 已选建议存在身份冲突\/混合来源，不能应用/);
  assert.match(page, /hiddenReviewPreview = hiddenNeedsReviewSkillSuggestions\.slice\(0, 3\)\.map\(skillSuggestionReviewSummary\)\.join\("\\n"\)/);
  assert.match(page, /hiddenMoreText = hiddenNeedsReviewSkillSuggestionCount > 3/);
  assert.match(page, /其中 \$\{hiddenNeedsReviewSkillSuggestionCount\} 条需人工判断/);
  assert.match(page, /还有 \$\{hiddenSelectedSkillSuggestionCount\} 条其他 Agent 已选建议，会一起应用到 Skill/);
  assert.match(page, /确认继续吗/);
  assert.match(page, /void compileTrainingSkills\(\)/);
  assert.match(page, /onClick=\{compileAllSelectedTrainingSkills\}/);
  assert.match(page, /应用全部已选 Skill/);
  assert.match(page, /应用全部已选/);
  assert.match(page, /hiddenSelectedSkillSuggestionCount\} 条其他 Agent 已选，其中 \{hiddenNeedsReviewSkillSuggestionCount\} 条需人工判断、\{hiddenBlockedSkillSuggestionCount\} 条身份冲突/);
  assert.match(page, /全部已选里有 \{selectedNeedsReviewSkillSuggestionCount\} 条需人工判断、\{selectedBlockedSkillSuggestionCount\} 条禁止应用/);
  assert.match(page, /点击“应用全部已选”会先做身份校验/);
  assert.match(page, /className="training-summary skill-suggestion-hint"/);
  assert.match(page, /当前筛选没有已选建议/);
  assert.match(page, /filteredUnselectedSafeSkillSuggestionCount\} 条/);
  assert.match(page, /filteredNeedsReviewSkillSuggestionCount\} 条需人工判断/);
  assert.match(page, /当前筛选还有 \{filteredUnselectedSkillSuggestionCount\} 条未选建议/);
  assert.match(page, /全选当前筛选”会包含这些未展示建议/);
  assert.match(page, /void changeTrainingSampleQualityFilter\(importedChatFilter, importedChatId\)/);
  assert.match(page, /setMessage\(importSummary \|\|/);
  assert.match(page, /trainingSampleImportFilterId/);
  assert.match(page, /setTrainingSampleImportFilterId\(importId\)/);
  assert.match(page, /importId: trainingSampleImportFilterId \|\| undefined/);
  assert.match(page, /function changeTrainingSampleQualityFilterInReviewScope\(filter: TrainingSampleQualityFilter\)/);
  assert.match(page, /changeTrainingSampleQualityFilter\(filter, trainingSampleImportFilterId\)/);
  assert.match(page, /className="training-import-history"/);
  assert.match(page, /chatImports\.slice\(0, 4\)\.map/);
  assert.match(page, /changeTrainingSampleQualityFilter\(chatImportPreferredQualityFilter\(item\), item\.id\)/);
  assert.match(page, /chatImportSceneSummaryLabel\(item\)/);
  assert.match(page, /function chatImportReviewCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportRejectedCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportReadyCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportNeedsReview\(item: ChatImport\)/);
  assert.match(page, /function chatImportReadyForSkill\(item: ChatImport\)/);
  assert.match(page, /function chatImportSkillSuggestionFilter\(item: ChatImport, suggestions: SkillSuggestion\[\]\)/);
  assert.match(page, /function chatImportPreferredQualityFilter\(item: ChatImport\): TrainingSampleQualityFilter/);
  assert.match(page, /if \(chatImportReviewCount\(item\) > 0\) return "review"/);
  assert.match(page, /chatImportReadyForSkill\(activeTrainingImport\)/);
  assert.match(page, /function focusChatImportSkillSuggestions\(item: ChatImport\)/);
  assert.match(page, /const safeKeys = targetSuggestions\.filter\(isSkillSuggestionAutoSelected\)\.map\(skillSuggestionKey\)/);
  assert.match(page, /setSkillSuggestionAgentFilter\(agentFilter\);\s*setSkillSuggestionSafetyFilter\("all"\);/);
  assert.match(page, /setSkillSuggestionAgentFilter\(agentSuggestionKey\);\s*setSkillSuggestionSafetyFilter\("all"\);/);
  assert.match(page, /setSkillSuggestionAgentFilter\(agent\.agentId \|\| agent\.agentKey \|\| "all"\);\s*setSkillSuggestionSafetyFilter\("all"\);/);
  assert.match(page, /setSelectedSkillSuggestionKeys\(\(current\) => \[\.\.\.new Set\(\[\.\.\.current, \.\.\.safeKeys\]\)\]\)/);
  assert.match(page, /onClick=\{\(\) => focusChatImportSkillSuggestions\(activeTrainingImport\)\}/);
  assert.match(page, /setTrainingWorkbenchView\("skills"\)/);
  assert.match(page, /查看 Skill 进化/);
  assert.match(page, /已确认 \$\{readyCount\} 条，可生成 Skill/);
  assert.match(page, /已切到本次导入列表；确认前不会进入训练/);
  assert.match(page, /activeTrainingImport/);
  assert.match(page, /scopedTrainingOverview/);
  assert.match(listSection, /导入批次：\$\{activeTrainingImport\.name\}/);
  assert.match(listSection, /清除批次/);
  assert.match(actionSection, /function trainingSampleReadyBlockingReasons\(sample: TrainingSample\)/);
  assert.match(page, /function trainingSampleRequiredFieldBlockingReasons\(sample: TrainingSample\)/);
  assert.match(page, /reasons\.push\("缺少 Agent"\)/);
  assert.match(page, /reasons\.push\("缺少场景"\)/);
  assert.match(page, /reasons\.push\("缺少客户问题"\)/);
  assert.match(page, /reasons\.push\("缺少标准回复"\)/);
  assert.match(page, /reasons\.push\("缺少 Skill 提示"\)/);
  assert.match(actionSection, /return trainingSampleRequiredFieldBlockingReasons\(sample\)/);
  assert.match(actionSection, /const blockingReasons = trainingSampleReadyBlockingReasons\(sample\)/);
  assert.match(actionSection, /window\.alert\(`这条训练样本还不能进入训练：\$\{blockingReasons\.join\("、"\)\}。请补齐后再确认。`\)/);
  assert.match(actionSection, /function trainingSampleBatchBlockingSummary\(samples: TrainingSample\[\]\)/);
  assert.match(actionSection, /const blockedSamples = samples/);
  assert.match(actionSection, /trainingSampleReadyBlockingReasons\(sample\)/);
  assert.match(actionSection, /本批有 \$\{blockedSamples\.length\} 条训练样本缺少必填信息/);
  assert.match(actionSection, /缺项预览/);
  assert.match(actionSection, /function confirmTrainingSampleReady\(sample: TrainingSample\)/);
  assert.match(actionSection, /const needsAttention = isTrainingSampleNeedingManualReview\(sample\)/);
  assert.match(actionSection, /const sceneUncertain = isSceneUncertainTrainingSample\(sample\)/);
  assert.match(actionSection, /trainingSampleAttentionReviewSummary\(sample\)/);
  assert.match(actionSection, /trainingSampleSceneReviewSummary\(sample\)/);
  assert.match(actionSection, /这条训练样本仍有风险，确认直接进入训练吗/);
  assert.match(actionSection, /status === "ready" && !confirmTrainingSampleReady\(sample\)/);
  assert.match(actionSection, /batchUpdateTrainingSampleStatus\(status: "ready" \| "review" \| "rejected", scope: "selected" \| "visible"\)/);
  assert.match(actionSection, /batchReviewTrainingSamples/);
  assert.match(actionSection, /const blockingSummary = status === "ready" \? trainingSampleBatchBlockingSummary\(candidates\) : ""/);
  assert.match(actionSection, /window\.alert\(blockingSummary\)/);
  assert.match(actionSection, /已拦截批量确认：请先补齐缺少必填信息的训练样本/);
  assert.match(actionSection, /const needsAttentionSamples = candidates\.filter\(isTrainingSampleNeedingManualReview\)/);
  assert.match(actionSection, /trainingSampleNeedsAttentionBatchWarning\(needsAttentionSamples\.length, needsAttentionSamples\)/);
  assert.match(actionSection, /const sceneUncertainSamples = candidates\.filter\(isSceneUncertainTrainingSample\)/);
  assert.match(actionSection, /const sceneUncertainCount = sceneUncertainSamples\.length/);
  assert.match(actionSection, /trainingSampleSceneBatchWarning\(sceneUncertainCount, sceneUncertainSamples\)/);
  assert.match(actionSection, /`\$\{needsAttentionWarning\}\$\{sceneUncertainWarning\}\$\{overflowText\}`/);
  assert.match(actionSection, /trainingSampleBatchReviewNote\(status, scopeLabel, sceneUncertainCount, needsAttentionSamples\.length\)/);
  assert.match(page, /function trainingSampleAttentionReviewSummary\(sample: TrainingSample\)/);
  assert.match(page, /const reason = sampleAttentionReasons\(sample\)\[0\]\?\.label \|\| sampleQualityReason\(sample\)/);
  assert.match(page, /function trainingSampleNeedsAttentionBatchWarning\(count: number, samples: TrainingSample\[\] = \[\]\)/);
  assert.match(page, /samples\.slice\(0, 3\)\.map\(trainingSampleAttentionReviewSummary\)\.join\("\\n"\)/);
  assert.match(page, /本次需处理样本预览/);
  assert.match(page, /低质量样本污染智能体/);
  assert.match(page, /function trainingSampleSceneReviewSummary\(sample: TrainingSample\)/);
  assert.match(page, /const customerText = skillSuggestionEvidencePreview\(sample\.customerText\)/);
  assert.match(page, /const keywordText = sampleSceneEvidence\(sample\)\.slice\(0, 3\)\.join\("、"\)/);
  assert.match(page, /sampleSceneCheckLabel\(sample\)/);
  assert.match(saveEditSection, /function editedTrainingSampleForConfirm\(sample: TrainingSample, edit: TrainingSampleEdit, status: "ready" \| "review"\): TrainingSample/);
  assert.match(saveEditSection, /agentKey: edit\.agentKey/);
  assert.match(saveEditSection, /scene: edit\.scene/);
  assert.match(saveEditSection, /customerText: edit\.customerText/);
  assert.match(saveEditSection, /idealReply: edit\.idealReply/);
  assert.match(saveEditSection, /skillHints: splitTextList\(edit\.skillHints\)/);
  assert.match(saveEditSection, /const nextSample = editedTrainingSampleForConfirm\(sample, sampleEdit, status\)/);
  assert.match(saveEditSection, /confirmTrainingSampleReady\(nextSample\)/);
  assert.match(saveEditSection, /saveTrainingSampleEdit\(sample: TrainingSample, status: "ready" \| "review"\)/);
  assert.match(saveEditSection, /if \(status === "ready" && !confirmTrainingSampleReady\(nextSample\)\) return/);
  assert.match(saveEditSection, /保存并确认样本/);
  assert.match(page, /function trainingSampleSceneBatchWarning\(count: number, samples: TrainingSample\[\] = \[\]\)/);
  assert.match(page, /samples\.slice\(0, 3\)\.map\(trainingSampleSceneReviewSummary\)\.join\("\\n"\)/);
  assert.match(page, /本次待确认样本预览/);
  assert.match(page, /还有 \$\{count - 3\} 条场景待确认样本未展示/);
  assert.match(page, /function trainingSampleBatchReviewNote\(/);
  assert.match(page, /needsAttentionCount = 0/);
  assert.match(page, /needsAttentionCount > 0 \? `\$\{needsAttentionCount\} 条需人工处理样本已人工确认` : ""/);
  assert.match(page, /sceneUncertainCount > 0 \? `\$\{sceneUncertainCount\} 条场景待确认样本已按当前 Agent 和场景人工确认` : ""/);
  assert.match(page, /riskParts\.join\("，"\)/);
  assert.match(page, /function isTrainingSampleNeedingManualReview\(sample: TrainingSample\)/);
  assert.match(page, /\| "needs_attention"/);
  assert.match(page, /changeTrainingSampleQualityFilter\("needs_attention"\)/);
  assert.match(page, /changeTrainingSampleQualityFilter\("scene_uncertain"\)/);
  assert.match(page, /changeTrainingSampleQualityFilter\(attentionReasonQualityFilter\(reason\)\)/);
  assert.match(page, /function attentionReasonQualityFilter\(reason: \{ code\?: string \}\): TrainingSampleQualityFilter/);
  assert.match(page, /filter === "needs_attention"/);
  assert.match(page, /filter === "scene_uncertain"/);
  assert.match(page, /isSceneUncertainTrainingSample\(sample\)/);
  assert.match(page, /function chatImportSceneSummary\(result: ChatImport\)/);
  assert.match(page, /function chatImportSceneUncertainCount\(item: ChatImport\)/);
  assert.match(page, /function chatImportSceneSummaryLabel\(item: ChatImport\)/);
  assert.match(page, /clearSceneCount = samples\.filter\(\(sample\) => sample\.sceneCheck\?\.status === "clear"\)\.length/);
  assert.match(page, /summary\.sceneUncertainSamples \?\? fallbackCount/);
  assert.match(page, /visibleTrainingRecommendations\(trainingOverview\.recommendations\)/);
  assert.doesNotMatch(page, /trainingOverview\.recommendations\.slice\(0, 2\)/);
  assert.match(page, /function trainingRecommendationPriority\(text: string\)/);
  assert.match(page, /聊天导入样本的场景不够确定\|自动分流记忆/);
  assert.match(page, /className="training-summary-action"/);
  assert.match(page, /setTrainingWorkbenchView\("review"\)/);
  assert.match(page, /查看场景待确认/);
  assert.match(page, /选择场景待确认/);
  assert.match(page, /当前显示样本里没有场景待确认的导入样本/);
  assert.match(page, /请逐条核对 Agent 和场景后再确认训练/);
  assert.match(page, /避免把 A 客户场景训练给 B 智能体/);
  assert.match(page, /已按当前 Agent 和场景人工确认/);
  assert.match(page, /场景待确认/);
  assert.match(page, /isAntiWrongReplyTrainingSample\(sample\) && sample\.status !== "review"/);
  assert.match(page, /className="training-attention-reasons"/);
  assert.match(page, /sampleAttentionReasons\(sample\)/);
  assert.match(page, /sampleSceneEvidence\(sample\)/);
  assert.match(page, /className="sample-scene-check"/);
  assert.match(page, /sampleSceneRouteMemoryBadge\(sample\)/);
  assert.match(page, /人工已确认/);
  assert.match(page, /确认后才分流/);
  assert.match(page, /可训练分流/);
  assert.match(page, /className="sample-attention-reasons"/);
  assert.match(page, /attentionReasonLabel\(reason\)/);
  assert.match(page, /title=\{attentionReasonTitle\(reason\)\}/);
  assert.match(rowSection, /<button\s+type="button"\s+key=\{reason\.code\}/);
  assert.match(rowSection, /onClick=\{\(\) => changeTrainingSampleQualityFilterInReviewScope\(attentionReasonQualityFilter\(reason\)\)\}/);
  assert.match(page, /sceneReasonCodes\.has\(reason\.code \|\| ""\)\) return "scene_uncertain"/);
  assert.match(page, /selectedTrainingSamplesMissingRequired = selectedVisibleTrainingSamples\.filter/);
  assert.match(page, /trainingSampleReadyBlockingReasons\(sample\)\.length/);
  assert.match(page, /\| "missing_required"/);
  assert.match(page, /return filter === "all" \|\| filter === "missing_required" \? undefined : filter/);
  assert.match(page, /missing_required: fallbackCount/);
  assert.match(page, /\{ key: "missing_required", label: "缺必填项" \}/);
  assert.match(page, /if \(filter === "missing_required"\) return trainingSampleRequiredFieldBlockingReasons\(sample\)\.length > 0/);
  assert.match(page, /const missingRequiredTrainingSamples = trainingSamples\.filter\(\(sample\) => trainingSampleReadyBlockingReasons\(sample\)\.length\)/);
  assert.match(page, /trainingSampleQualityFilter === "missing_required" \? missingRequiredTrainingSamples\.length : trainingSamples\.length/);
  assert.match(page, /const visibleTrainingSamples = trainingSampleQualityFilter === "missing_required" \? missingRequiredTrainingSamples : trainingSamples/);
  assert.match(listSection, /changeTrainingSampleQualityFilterInReviewScope\("missing_required"\)/);
  assert.match(listSection, /onClick=\{\(\) => changeTrainingSampleQualityFilterInReviewScope\("missing_required"\)\}/);

  assert.match(listSection, /只看缺项/);
  assert.match(page, /function selectTrainingSamplesMissingRequired\(\)/);
  assert.match(page, /const matchingSamples = visibleTrainingSamples\.filter\(\(sample\) => trainingSampleReadyBlockingReasons\(sample\)\.length\)/);
  assert.match(page, /setSelectedTrainingSampleIds\(\(current\) => \[\.\.\.new Set\(\[\.\.\.current, \.\.\.samples\.map\(\(sample\) => sample\.id\)\]\)\]\)/);
  assert.match(page, /已选择 \$\{samples\.length\} 条缺必填项样本/);
  assert.match(page, /const missingRequiredCount = samples\.filter\(\(sample\) => trainingSampleReadyBlockingReasons\(sample\)\.length\)\.length/);
  assert.match(page, /if \(missingRequiredCount\) parts\.push\(`\$\{missingRequiredCount\} 条缺必填项`\)/);
  assert.match(page, /selectedMissingRequiredTrainingSampleCount = selectedTrainingSamplesMissingRequired\.length/);
  assert.match(page, /selectedMissingRequiredTrainingSample = selectedTrainingSamplesMissingRequired\[0\] \|\| null/);
  assert.match(page, /selectedMissingRequiredTrainingSample \|\|\n\s+selectedVisibleTrainingSamples\.find\(isTrainingSampleNeedingManualReview\)/);
  assert.match(page, /visibleTrainingSamplesMissingRequired = visibleTrainingSamples\.filter/);
  assert.match(page, /visibleMissingRequiredTrainingSampleCount = visibleTrainingSamplesMissingRequired\.length/);
  assert.match(page, /visibleMissingRequiredTrainingSample \|\|\n\s+visibleTrainingSamples\.find\(isTrainingSampleNeedingManualReview\)/);
  assert.match(page, /selectedNeedsAttentionTrainingSampleCount = selectedVisibleTrainingSamples\.filter\(isTrainingSampleNeedingManualReview\)\.length/);
  assert.match(page, /selectedSceneUncertainTrainingSampleCount = selectedVisibleTrainingSamples\.filter\(isSceneUncertainTrainingSample\)\.length/);
  assert.match(page, /selectedRiskTrainingSample =/);
  assert.match(page, /selectedVisibleTrainingSamples\.find\(isTrainingSampleNeedingManualReview\)/);
  assert.match(page, /selectedVisibleTrainingSamples\.find\(isSceneUncertainTrainingSample\)/);
  assert.match(page, /visibleRiskTrainingSample =/);
  assert.match(page, /visibleTrainingSamples\.find\(isTrainingSampleNeedingManualReview\)/);
  assert.match(page, /visibleNeedsAttentionTrainingSampleCount = visibleTrainingSamples\.filter\(isTrainingSampleNeedingManualReview\)\.length/);
  assert.match(page, /visibleSceneUncertainTrainingSampleCount = visibleTrainingSamples\.filter\(isSceneUncertainTrainingSample\)\.length/);
  assert.match(listSection, /已选 \{selectedVisibleTrainingSamples\.length\} 条/);
  assert.match(listSection, /selectedMissingRequiredTrainingSampleCount \? `，\$\{selectedMissingRequiredTrainingSampleCount\} 条缺必填项` : ""/);
  assert.match(listSection, /selectedMissingRequiredTrainingSampleCount > 0/);
  assert.match(listSection, /onClick=\{selectTrainingSamplesMissingRequired\}/);
  assert.match(listSection, /disabled=\{Boolean\(busy\) \|\| !visibleMissingRequiredTrainingSampleCount\}/);
  assert.match(listSection, /选择缺项/);
  assert.match(listSection, /请先补齐已选样本的必填信息/);
  assert.match(listSection, /已选样本缺少必填项/);
  assert.match(listSection, /缺必填项的样本不能进入训练/);
  assert.match(listSection, /编辑首条缺项/);
  assert.match(listSection, /visibleMissingRequiredTrainingSampleCount \? `\$\{visibleMissingRequiredTrainingSampleCount\} 条缺必填项` : ""/);
  assert.match(listSection, /当前显示里有缺项样本/);
  assert.match(listSection, /selectedNeedsAttentionTrainingSampleCount \? `，\$\{selectedNeedsAttentionTrainingSampleCount\} 条需处理` : ""/);
  assert.match(listSection, /selectedSceneUncertainTrainingSampleCount \? `，其中 \$\{selectedSceneUncertainTrainingSampleCount\} 条场景待确认` : ""/);
  assert.match(listSection, /className="sample-selection-risk"/);
  assert.match(listSection, /已选样本需要复核/);
  assert.match(listSection, /已选确认.*会把这些样本写成人工确认记录/s);
  assert.match(listSection, /className="sample-selection-risk muted"/);
  assert.match(listSection, /当前显示里有待复核样本/);
  assert.match(listSection, /使用“智能选择需处理”或“选择场景待确认”/);
  assert.match(listSection, /className="sample-selection-risk-actions"/);
  assert.match(listSection, /startSampleEdit\(selectedRiskTrainingSample\)/);
  assert.match(listSection, /startSampleEdit\(visibleRiskTrainingSample\)/);
  assert.match(listSection, /编辑首条风险/);
  assert.match(listSection, /changeTrainingSampleQualityFilterInReviewScope\("needs_attention"\)/);
  assert.match(listSection, /changeTrainingSampleQualityFilterInReviewScope\("scene_uncertain"\)/);
  assert.match(listSection, /onClick=\{selectTrainingSamplesNeedingReview\}/);
  assert.match(listSection, /onClick=\{selectSceneUncertainTrainingSamples\}/);
  assert.match(listSection, /只看需处理/);
  assert.match(listSection, /选择需处理/);
  assert.match(listSection, /已选确认/);
  assert.match(listSection, /已选退回复核/);
  assert.match(listSection, /已选禁用/);
  assert.match(listSection, /changeTrainingSampleQualityFilterInReviewScope\(option\.key\)/);
  assert.match(rowSection, /const requiredFieldReasons = trainingSampleReadyBlockingReasons\(sample\)/);
  assert.match(rowSection, /className="sample-required-reasons"/);
  assert.match(rowSection, /aria-label="训练样本缺必填项"/);
  assert.match(rowSection, /requiredFieldReasons\.map\(\(reason\) =>/);
  assert.match(rowSection, /key=\{reason\}/);
  assert.match(rowSection, /changeTrainingSampleQualityFilterInReviewScope\("missing_required"\)/);
  assert.match(rowSection, /\{reason\}/);  assert.match(rowSection, /className="sample-check"/);
  assert.match(page, /function skillSuggestionScopeTone\(suggestion: SkillSuggestion\)/);
  assert.match(page, /function skillSuggestionScopeLabel\(suggestion: SkillSuggestion\)/);
  assert.match(page, /function skillSuggestionScopeDetail\(suggestion: SkillSuggestion\)/);
  assert.match(page, /skillSuggestionScopeLabel\(suggestion\)/);
  assert.match(page, /skillSuggestionScopeDetail\(suggestion\)/);
  assert.match(page, /className=\{`skill-suggestion-scope \$\{scopeTone\}`\}/);
  assert.match(page, /className=\{`skill-suggestion-scope-note \$\{scopeTone\}`\}/);
  assert.match(page, /作用范围/);
  assert.match(page, /这条建议还没有范围信息，应用前需要先核对样本来源。/);
  assert.match(rowSection, /toggleTrainingSampleSelection\(sample\.id, event\.target\.checked\)/);
  assert.match(page, /className="sample-edit-risk-note"/);
  assert.match(page, /保存前先核对/);
  assert.match(page, /先确认客户原话、客服回复、Agent 和场景都对应同一个客户问题/);
  assert.match(page, /attentionReasons\.slice\(0, 3\)\.map/);
  assert.match(page, /sampleSceneCheckLabel\(sample\)/);
  assert.match(rowSection, /const editingPreviewSample = isEditingSample && sampleEdit \? editedTrainingSampleForConfirm\(sample, sampleEdit, "ready"\) : null/);
  assert.match(rowSection, /const editingBlockingReasons = editingPreviewSample \? trainingSampleReadyBlockingReasons\(editingPreviewSample\) : \[\]/);
  assert.match(rowSection, /补齐后才能训练/);
  assert.match(rowSection, /sample-edit-risk-tags blocking/);
  assert.match(rowSection, /disabled=\{Boolean\(busy\) \|\| editingBlockingReasons\.length > 0\}/);
  assert.match(rowSection, /请先补齐：\$\{editingBlockingReasons\.join\("、"\)\}/);
  assert.match(saveEditSection, /function editedTrainingSampleForConfirm\(sample: TrainingSample, edit: TrainingSampleEdit, status: "ready" \| "review"\): TrainingSample/);
  assert.match(saveEditSection, /agentKey: edit\.agentKey/);
  assert.match(saveEditSection, /scene: edit\.scene/);
  assert.match(saveEditSection, /customerText: edit\.customerText/);
  assert.match(saveEditSection, /idealReply: edit\.idealReply/);
  assert.match(saveEditSection, /skillHints: splitTextList\(edit\.skillHints\)/);
  assert.match(saveEditSection, /const nextSample = editedTrainingSampleForConfirm\(sample, sampleEdit, status\)/);
  assert.match(saveEditSection, /confirmTrainingSampleReady\(nextSample\)/);
  assert.match(saveEditSection, /saveTrainingSampleEdit\(sample: TrainingSample, status: "ready" \| "review"\)/);
  assert.match(saveEditSection, /if \(status === "ready" && !confirmTrainingSampleReady\(nextSample\)\) return/);
  assert.match(saveEditSection, /保存并确认样本/);
  assert.match(css, /\.sample-required-reasons/);
  assert.match(css, /\.sample-required-reasons strong,/);
  assert.match(css, /\.sample-required-reasons button/);
  assert.match(css, /\.sample-required-reasons button:disabled/);  assert.match(css, /\.sample-selection-summary/);
  assert.match(css, /\.skill-suggestion-scope/);
  assert.match(css, /\.skill-suggestion-scope\.risk/);
  assert.match(css, /\.skill-suggestion-scope-note/);
  assert.match(css, /\.skill-suggestion-scope-note\.risk/);
  assert.match(css, /\.sample-selection-risk/);
  assert.match(css, /\.sample-selection-risk\.muted/);
  assert.match(css, /\.sample-selection-risk-actions/);
  assert.match(css, /\.sample-selection-risk-actions button/);
  assert.match(css, /\.sample-check input/);
  assert.match(css, /\.sample-edit-risk-note/);
  assert.match(css, /\.sample-edit-risk-tags/);
  assert.match(css, /\.sample-edit-risk-tags\.blocking em/);
  assert.match(css, /\.training-attention-reasons/);
  assert.match(css, /\.training-summary-action/);
  assert.match(css, /\.training-summary-action:disabled/);
  assert.match(css, /\.training-import-history/);
  assert.match(css, /\.training-import-row\.needs-review/);
  assert.match(css, /\.training-import-row\.clear/);
  assert.match(css, /\.sample-scene-check/);
  assert.match(css, /\.sample-scene-check span\.route-memory-ok/);
  assert.match(css, /\.sample-scene-check span\.route-memory-blocked/);
  assert.match(css, /\.sample-attention-reasons/);
  assert.match(css, /\.sample-attention-reasons button/);
  assert.match(css, /\.sample-attention-reasons button:disabled/);
  assert.match(api, /sceneUncertainSamples\?: number/);
  assert.match(api, /\| "scene_uncertain"/);
  assert.match(api, /importId\?: string/);
  assert.match(api, /params\.set\("importId", filters\.importId\)/);
  assert.match(api, /sceneSummary\?: \{/);
  assert.match(api, /sceneUncertainCount: number/);
  assert.match(api, /readyCount\?: number/);
  assert.match(api, /reviewCount\?: number/);
  assert.match(api, /rejectedCount\?: number/);
});
